import type { Metadata } from "next";
import "./globals.css";
import Menu from "../components/Menu";

export const metadata: Metadata = {
  title: "Teste",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="flex flex-col h-screen w-screen md:flex-row">
          <div className="order-2 md:order-1">
            <Menu />
          </div>
          <div className="order-1 h-screen w-screen md:order-2">{children}</div>
        </div>
      </body>
    </html>
  );
}
